### PR TITLE
WIP: Default Message

### PR DESCRIPTION
**Pull request by josephbondoc**
I need help setting the container to the middle of the viewport without using css hacks like top and bottom. Thanks!

### CODE REVIEW

**Comment by josephbondoc** [comment]
image

Heres my current viewport. I want this to be in the middle of the screen

**Comment by josephbondoc** [comment]
Hello team~

So I've considered your fixes and I included inline styles for my parent component

However, it it now not showing. It only shows if I use position:absolute

very confusion! help! Please review my code

**Comment by josephbondoc** [comment]
Never mind! I have found the fix. I had multiple conflicting Flex:1'! thank you for your help guys

**Comment by josephbondoc** [comment]
Help on creating props for my component!

**Comment by KaanDarcey** [comment]
Hey J, to add a prop simply put the name of the prop in curly bracakets inside the functions brackets, for example: function({prop})
after doing that any value can be passed into component as such:
<component prop='value' />
if you want a default value add the following to your code after the function but before the export default:
componentName.defaultProps = {
prop: 'value'
};

**Comment by josephbondoc** [comment]
Got it! Thanks Kaan and Abhi for your input.

I have now configured a color change prop for my component and it should be good to go to combine for Level 3! :) :) :)

**Pull request merged**
